# Archivo generado por el Instalador de Alba el %TIMESTAMP%
dev:
  propel:
    param:
      classname:    DebugPDO

test:
  propel:
    param:
      classname:    DebugPDO

all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          mysql:dbname=alba;host=localhost
      username:     administrador
      password:     upN2XuOQ5u5u
      enconding:    utf8
      classname:    PropelPDO
      datasource:   propel
